### ISSUE TITLE
请大佬帮忙看下附件中的apk转化后无法打开

### ISSUE THREAD

**Issue by Kerr1Gan** [amimo/dcc#14]
在Application类中加载了so，能正常安装但是打不开，希望大佬帮忙看看，原始的apk在附件中，感谢。
[app.apk.zip](https://github.com/amimo/dcc/files/3997643/app.apk.zip)

**Comment by amimo** [comment]
报什么错

**Comment by Kerr1Gan** [comment]
2019-12-24 16:36:12.149 4023-4023/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tasuang.haru, PID: 4023
    java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.app.ActivityThread.installProvider(ActivityThread.java:6533)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6021)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5927)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.support.v4.content.FileProvider.b(Unknown Source:31)
        at android.support.v4.content.FileProvider.a(Unknown Source:13)
        at android.support.v4.content.FileProvider.attachInfo(Unknown Source:29)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6528)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6021) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5927) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Kerr1Gan** [comment]
转化后logo变成Android默认的图标了，原有的没有显示。

**Comment by amimo** [comment]
应该是apktool的问题,我把apktool换成[https://github.com/rover12421/ShakaApktool](https://github.com/rover12421/ShakaApktool),用multidex分支加固是可以跑起来的.

**Comment by Kerr1Gan** [comment]
正常了 感谢大佬
