### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by TheInterestingSoul** [amimo/dcc#3]
### 复现过程
按照README.MD配置好后，执行
`root@localhost:/****/Dex2C# python3.7 dcc.py t.apk -o o.apk`
运行结果
```
[ERROR   ] dcc: Compile t.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 370, in <module>
    dcc(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 330, in dcc
    os.rename(src_zip, source_archive)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmplal_8cse-dcc.zip' -> 'project-source.zip'
[INFO    ] dcc: removing /tmp/dcc-project-hlpqh92y
[INFO    ] dcc: removing /tmp/tmplal_8cse-dcc
```
### 环境
Python 3.7.3
Ubuntu 19.04 ~on [Termux](https://www.coolapk.com/apk/com.termux) 0.74~

**Comment by amimo** [comment]
用最新的代码试试

**Comment by TheInterestingSoul** [comment]
还是没有解决cross device rename，只是文件变成shutil.py了
```
[ERROR   ] dcc: Compile t.apk failed!
Traceback (most recent call last):
  File "/usr/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpm9fzjt__-dcc.zip' -> 'project-source.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dcc.py", line 374, in <module>
    dcc(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 334, in dcc
    shutil.move(src_zip, source_archive)
  File "/usr/lib/python3.7/shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.7/shutil.py", line 264, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 205, in copystat
    follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted
[INFO    ] dcc: removing /tmp/dcc-project-0sl3ev5r
[INFO    ] dcc: removing /tmp/tmpm9fzjt__-dcc
```

**Comment by amimo** [comment]
看起来是个新的问题.
我怀疑可能跟你的文件系统有关系,当前目录的文件系统是不是fat格式或者是网络挂载过来的?
你可以尝试把代码复制到/tmp目录操作,这样应该没有问题.

**Comment by GoFly233** [comment]
Ubuntu 19.04 on Termux 0.74
划重点，Termux😂
试下cp到/tmp，看下能不能运行
（怕是AIDE写程序）（小声bb）

**Comment by TheInterestingSoul** [comment]
> Ubuntu 19.04 on Termux 0.74
> 划重点，Termux
> 试下cp到/tmp，看下能不能运行
> （怕是AIDE写程序）（小声bb）

dcc要引用ndk和sdk，手机还没有root，只有整套3.7GB一起复制到/tmp然后还要chmod...（手动滑稽）

**Comment by amimo** [comment]
只需要复制dcc就可以了,ndk,sdk不需要复制.
或者使用你指定的临时目录
```
cd dcc
mkdir tmp
TMPDIR=tmp python3.7 dcc.py t.apk -o o.apk

**Comment by TheInterestingSoul** [comment]
> 只需要复制dcc就可以了,ndk,sdk不需要复制.
> 或者使用你指定的临时目录
> 
> ```
> cd dcc
> mkdir tmp
> TMPDIR=tmp python3.7 dcc.py t.apk -o o.apk
> ```

没得搞，手机没root，ndk-build执行不了

**Comment by amimo** [comment]
😂我周末我搞下windows

**Comment by TheInterestingSoul** [comment]
ndk貌似不支持aarch64
看来我有必要把我那台落灰的的惠普拿出来装个真的Ubuntu了🤔

**Comment by TheInterestingSoul** [comment]
先close了，有新bug再开另外的
