### ISSUE TITLE
Exception: unkonw type vResult_43

### ISSUE THREAD

**Issue by 1767523953** [amimo/dcc#47]
```
owner@ubuntu:~/Desktop/github/dcc$ python3 dcc.py app-release.apk -o out.apk
[WARNING ] androguard.core.api_specific_resources: Requested API level 30 is larger than maximum we have, returning API level 28 instead.
[WARNING ] dcc: compile method failed:Lcom/common/security/PS;run()V (unkonw type vResult_43)
Traceback (most recent call last):
  File "dcc.py", line 369, in compile_dex
    code = compiler.get_source_method(m)
  File "/home/owner/Desktop/github/dcc/dex2c/compiler.py", line 557, in get_source_method
    irmethod = z.process()
  File "/home/owner/Desktop/github/dcc/dex2c/compiler.py", line 170, in process
    self.build()
  File "/home/owner/Desktop/github/dcc/dex2c/compiler.py", line 207, in build
    self.verify_operand_type()
  File "/home/owner/Desktop/github/dcc/dex2c/compiler.py", line 229, in verify_operand_type
    raise Exception('unkonw type %s' % var)
Exception: unkonw type vResult_43
[WARNING ] dcc: ================================
[WARNING ] dcc: Lcom/common/security/PS;run()V:unkonw type vResult_43
[WARNING ] dcc: ================================

```

**Comment by 1767523953** [comment]
是否需要提供原smali文件？

**Comment by amimo** [comment]
类型推导失败了。
解这个问题需要更深入的研究类型推导，暂时无法解决。

**Comment by 1767523953** [comment]
好的，明白
