### ISSUE TITLE
win10

### ISSUE THREAD

**Issue by 1198287349** [amimo/dcc#49]
Traceback (most recent call last):
  File "dcc.py", line 450, in <module>
    dcc_cfg = json.load(fp)
  File "D:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 19 (char 56)

**Comment by amimo** [comment]
配置文件不是个合法的json格式，或者是配置文件里面有中文路径吧。

**Comment by icew4y** [comment]
> Traceback (most recent call last): File "dcc.py", line 450, in dcc_cfg = json.load(fp) File "D:\Python\lib\json__init__.py", line 293, in load return loads(fp.read(), File "D:\Python\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "D:\Python\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "D:\Python\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Invalid \escape: line 3 column 19 (char 56)



> Traceback (most recent call last): File "dcc.py", line 450, in dcc_cfg = json.load(fp) File "D:\Python\lib\json__init__.py", line 293, in load return loads(fp.read(), File "D:\Python\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "D:\Python\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "D:\Python\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Invalid \escape: line 3 column 19 (char 56)

你NDK路径没有加转义符 `\\`
