### ISSUE TITLE
WIN10 找不到指定文件报错

### ISSUE THREAD

**Issue by BaiLangXianSen** [amimo/dcc#52]
jni/nc/Dex2C.h:28:91: note: expanded from macro 'D2C_RESOLVE_FIELD'
  if (cached_field == NULL && d2c_resolve_field(env, &cached_class, &cached_field, false, class_name, field_name...
                                                                                          ^~~~~~~~~~
159 warnings generated.
[armeabi-v7a] SharedLibrary  : libnc.so
159 warnings generated.
[arm64-v8a] SharedLibrary  : libnc.so
[armeabi-v7a] Install        : libnc.so => libs/armeabi-v7a/libnc.so
[arm64-v8a] Install        : libnc.so => libs/arm64-v8a/libnc.so
make: Leaving directory 'C:/Users/70500/AppData/Local/Temp/dcc-project-ocgs4lpv'
I: Using Apktool 2.6.1 on your_app.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
[ERROR   ] dcc: Compile your_app.apk failed!
Traceback (most recent call last):
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 463, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 416, in dcc_main
    native_compiled_dexes(decompiled_dir, compiled_methods)
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 316, in native_compiled_dexes
    native_class_methods(smali_path, compiled_methods)
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 282, in native_class_methods
    line = next_line()
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 250, in next_line
    return fp.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbb in position 131: illegal multibyte sequence
[INFO    ] dcc: removing C:\Users\70500\AppData\Local\Temp\dcc-project-ocgs4lpv
Traceback (most recent call last):
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 467, in <module>
    clean_temp_files()
  File "C:\Users\70500\Desktop\dcc\dcc.py", line 60, in clean_temp_files
    shutil.rmtree(name)
  File "D:\DATA\汇编\Python\lib\shutil.py", line 747, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\DATA\汇编\Python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\DATA\汇编\Python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "D:\DATA\汇编\Python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 3 more times]
  File "D:\DATA\汇编\Python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\DATA\汇编\Python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\70500\\AppData\\Local\\Temp\\dcc-project-ocgs4lpv\\obj\\local\\arm64-v8a\\objs\\nc\\nc\\Java_com_e4a_runtime_components_impl_android__0767d_06d6a_05148_068ee_04e36_1_0652f_04ed8_09009_062e9_05bf9_08bdd_06846_07c7b_05e93_PayDialog_onCreate__Landroid_os_Bundle_2.o'

**Comment by BaiLangXianSen** [comment]
解决了  subprocess shell的问题

**Comment by amimo** [comment]
路径里面有中文吧

**Comment by BaiLangXianSen** [comment]
> 路径里面有中文吧

= = 我试试
